### ISSUE TITLE
Feature: User can sign out

### ISSUE THREAD

**Issue by derrick-fleming** [derrick-fleming/park-advisor#31]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign out of their account. 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After the user has logged in, the navigation bar will have a link that will prompt them to being able to sign out of their account. When user clicks 'sign out' they will be signed out of their account. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-12-01 at 12 16 49 PM](https://user-images.githubusercontent.com/109825222/205151044-2be0c8f1-8f9d-468f-841d-558435752664.png)

![Screen Shot 2022-12-01 at 12 16 24 PM](https://user-images.githubusercontent.com/109825222/205151035-9ee82b43-a4b0-466b-b965-5ba0690a2f57.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [ ] Update navigation bar component to include 'Sign Out' button if user is logged into their account
- [ ] Style button to look like a link that matches navigation bar
- [ ] Add an event listener to `removeItem()` from local storage 
- [ ]  Remove the 'park-reviews-jwt' token 
- [ ] Update the state to re-render
- [ ] Check that pages update appropriately and user account is not present 
- [ ] Check that infographic map directs user to sign-in page

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
